### ISSUE TITLE
Questions about how lnurl-auth impl works

### ISSUE THREAD

**Issue by straumat** [theborakompanioni/bitcoin-spring-boot-starter#111]
**Question**
In the lnurl_auth_linking_key table you create [here](https://github.com/theborakompanioni/bitcoin-spring-boot-starter/blob/master/incubator/spring-lnurl/spring-lnurl-auth-example-application/src/main/java/org/tbk/lightning/lnurl/example/db/migration/V1__init.java):

- Why do you store the least_recently_used_k1 ? when is this data queried ?
- Why is it the least recently used k1 instead of the most recently used k1 ?

**Question**
Why, in your example, do you separate LnurlAuthPairingService and WalletUserService ?
What do you think would be the problem to have WalletUserService implement LnurlAuthPairingService ?

**Question**
My question about spring session cookie was to know if you stored things like k1, encoded k1, or linking key in the
session ?

**Question**
My question about why do you store the k1 was a bit stupid. Indeed, my application needs to keep it to compare it later.
My front-end application may run on several servers. From what I understand, I need to store the k1 in the database or
in a shared cache (redis, memcached, etc.) to be able to retrieve it on all my servers.
Am I right?

**Question**
About the k1Manager declared by default. The only benefits from having one declared by default is to make it easier to
understand how to use the library. It's the same way Spring boot declare a default jdbc pool if you don't declare one.
It hides complexity for the newcomer.

**Comment by theborakompanioni** [comment]
> **Question** In the lnurl_auth_linking_key table you create [here](https://github.com/theborakompanioni/bitcoin-spring-boot-starter/blob/master/incubator/spring-lnurl/spring-lnurl-auth-example-application/src/main/java/org/tbk/lightning/lnurl/example/db/migration/V1__init.java):
> 
>     * Why do you store the least_recently_used_k1 ? when is this data queried ?

It is used to pair the `k1` to a user. Yeah, just to make it clear, this is just the implementation used in the example application.
1. Browser: A user visits the login page and a `k1` is generated.
2. Wallet:  Triggers auth request. In `pairK1WithLinkingKey` a user is fetched (or created if needed) and marked with that `k1`.
3. Browser: If user is not yet logged in we try to find one with `findPairedLinkingKeyByK1`

After that, the `k1` could be removed from the database.. which is just not done as it is a sample application. It could be removed to save disk space or just because it became unnecessary data.

>     * Why is it the least recently used k1 instead of the most recently used k1 ?

That is in fact just bad naming, it should be named `most_recently_used_k1` or just `current_k1`. I can see that this is a source for confusion. Thanks for making me aware of it.

> 
> 
> **Question** Why, in your example, do you separate LnurlAuthPairingService and WalletUserService ? What do you think would be the problem to have WalletUserService implement LnurlAuthPairingService ?

You can do whatever suits your application best. I think I just wanted to have them separated. 

> 
> **Question** My question about spring session cookie was to know if you stored things like k1, encoded k1, or linking key in the session ?

Yes, `k1` is saved in the session data when a user arrives at the login page ([LnurlAuthLoginPageGeneratingFilter#L129-L130](https://github.com/theborakompanioni/bitcoin-spring-boot-starter/blob/6a9a089638e2e2108d78338d2463a83727a3ad78/incubator/spring-lnurl/spring-lnurl-auth-security/src/main/java/org/tbk/spring/lnurl/security/ui/LnurlAuthLoginPageGeneratingFilter.java#L129-L130)). After a wallet provides a valid signature for that `k1` it will be paired to the provided public key (linking key) and potentially create a new user if you have never seen that key before ([LnurlAuthWalletAuthenticationProvider#L56](https://github.com/theborakompanioni/bitcoin-spring-boot-starter/blob/6a9a089638e2e2108d78338d2463a83727a3ad78/incubator/spring-lnurl/spring-lnurl-auth-security/src/main/java/org/tbk/spring/lnurl/security/wallet/LnurlAuthWalletAuthenticationProvider.java#L56)). In the web browser it will "transfer" the session over. After a successful migration, `k1` is removed from the session data ([LnurlAuthSessionAuthenticationFilter#L81-L83](https://github.com/theborakompanioni/bitcoin-spring-boot-starter/blob/6a9a089638e2e2108d78338d2463a83727a3ad78/incubator/spring-lnurl/spring-lnurl-auth-security/src/main/java/org/tbk/spring/lnurl/security/session/LnurlAuthSessionAuthenticationFilter.java#L81-L83)).

Please not that, if and when your application creates a session is entirely up to you. This is just how the starter would do it (e.g. `getSession(true)` in `LnurlAuthLoginPageGeneratingFilter` - trying retrieve the session if it is already present - or creating one otherwise).

> 
> **Question** My question about why do you store the k1 was a bit stupid. Indeed, my application needs to keep it to compare it later. My front-end application may run on several servers. From what I understand, I need to store the k1 in the database or in a shared cache (redis, memcached, etc.) to be able to retrieve it on all my servers. Am I right?

Yes, you are right. If it is kept in-memory, a log-in process would not be able to proceed if an instance is down or a requests gets loadbalanced to another instance.

> 
> **Question** About the k1Manager declared by default. The only benefits from having one declared by default is to make it easier to understand how to use the library. It's the same way Spring boot declare a default jdbc pool if you don't declare one. It hides complexity for the newcomer.

Not a question, is it? : )
Yes, the intention is that declaring a default `SimpleK1Manager`(in memory) should get users started quickly, but it is not suitable for "enterprise" applications.
Is this related to https://github.com/theborakompanioni/bitcoin-spring-boot-starter/issues/110 ?

Please let me know if that helped you in any way and made things a little bit more clear.

**Comment by straumat** [comment]
Thanks! Replies are great and I'm getting more and more at ease with everything.

The blog post i'm working on is now [here](https://github.com/royllo/explorer/tree/461-user-asset-data-management/docs/design/lnurl-auth). I think i will get some more questions (not a lot) while writing the article so I think the issue should be kept open if you are ok with it.

**Comment by theborakompanioni** [comment]
> Thanks! Replies are great and I'm getting more and more at ease with everything.
> 
> The blog post i'm working on is now [here](https://github.com/royllo/explorer/tree/461-user-asset-data-management/docs/design/lnurl-auth). I think i will get some more questions (not a lot) while writing the article so I think the issue should be kept open if you are ok with it.

Really nice! Thank you :pray: 
Of course, we can keep this issue open for all questions.
I might also use them to improve the readme of the example project.

However.. please know that the current code is not set in stone and may not support all use cases.
I am eager to learn how you want to use it and I am happy to include new features to support your business case.
(e.g. the current login page is the most basic thing that works - it is not suitable for enterprise apps and just a proof of concept).

**Comment by straumat** [comment]
Great, I will improve Royllo and you will improve `bitcoin-spring-boot-starter` on the way!
It's ok if the code change, the idea for me is also to to keep my `bitcoin-spring-boot-starter` tutorial up to date for people who wants to setup `bitcoin-spring-boot-starter`
