### ISSUE TITLE
Add support for advanced LightningJ APIs

### ISSUE THREAD

**Issue by cd2357** [theborakompanioni/bitcoin-spring-boot-starter#29]
Right now `lnd-grpc-client` creates injectable beans for the sync / async versions (`SynchronousLndAPI`, `AsynchronousLndAPI`) of the main LND API.

The main LND API exposes basic LND functionalities, but LightningJ also has more advanced ones.

As per [its documentation](https://www.lightningj.org/#_available_apis), it exposes several other API services, each with a sync + an async variant, for example:
* Wallet Unlocker API
  * `org.lightningj.lnd.wrapper.walletunlocker.SynchronousWalletUnlockerAPI`
  * `org.lightningj.lnd.wrapper.walletunlocker.AsynchronousWalletUnlockerAPI`
* Invoices API
  * `org.lightningj.lnd.wrapper.invoices.SynchronousInvoicesAPI`
  * `org.lightningj.lnd.wrapper.invoices.AsynchronousInvoicesAPI`
* etc

---

Could you please create beans for the other ones as well?

From what I can tell it comes down to extending
* `org.tbk.lightning.lnd.grpc.LndJsonRpcClientFactoryImpl` and
* `org.tbk.lightning.lnd.grpc.config.LndJsonRpcClientAutoConfiguration`

Thanks.

**Comment by theborakompanioni** [comment]
Hey @cd2357 - thank you very much! this is really appreciated!

This is implemented with commit https://github.com/theborakompanioni/bitcoin-spring-boot-starter/commit/a919dd44ae747b2316b1476cae1c8c548c189111 .
I will do some further testing and will release a new version soon.

Your issue was also the trigger to finally get rid of the erroneous term 'JsonRpc' in class names of this package.
This has also been fixed, as well as the health/info actuator property names (also contained the term 'jsonrpc').

The class `LndJsonRpcClientFactory` has been removed, as it served no real benefit to other users. 

Thank you for your time, sir.
Have a nice day.

**Comment by cd2357** [comment]
Excellent, that's great to hear @theborakompanioni  :)

Looking forward to the next release.

**Comment by theborakompanioni** [comment]
> Looking forward to the next release.

@cd2357 [v0.2.0](https://github.com/theborakompanioni/bitcoin-spring-boot-starter/releases/tag/0.2.0) has been released.

Would you report if that solved your problem, or if there is anything that you are missing from this release?
I'll close the issue if it satisfies your needs. 

Have a nice day. Thank you.

**Comment by cd2357** [comment]
Works, just tested 👍

I can close it right away.
